
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorCJ;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GUION = 8;
  public static final int DIFERENCIA = 5;
  public static final int OPERACION = 6;
  public static final int INTERSECCION = 3;
  public static final int FLECHA = 12;
  public static final int LLAVEC = 11;
  public static final int LLAVEA = 10;
  public static final int DOS_PUNTOS = 7;
  public static final int COMA = 13;
  public static final int EOF = 0;
  public static final int CONJ = 9;
  public static final int UNION = 2;
  public static final int PARENTESIS_C = 16;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 19;
  public static final int COMPLEMENTO = 4;
  public static final int PARENTESIS_A = 15;
  public static final int PUNTO_COMA = 17;
  public static final int ASCII = 18;
  public static final int EVALUAR = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UNION",
  "INTERSECCION",
  "COMPLEMENTO",
  "DIFERENCIA",
  "OPERACION",
  "DOS_PUNTOS",
  "GUION",
  "CONJ",
  "LLAVEA",
  "LLAVEC",
  "FLECHA",
  "COMA",
  "EVALUAR",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "PUNTO_COMA",
  "ASCII",
  "IDENTIFICADOR"
  };
}

